version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    environment:
      - VK_GROUP_TOKEN=${VK_GROUP_TOKEN}
      - VK_USER_TOKEN=${VK_USER_TOKEN}
      - VK_MAXIM_TOKEN=${VK_MAXIM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "80"
