services:
  web:
    build: .
    restart: unless-stopped
    expose:
      - "80"
  api:
    build: ./api
    restart: unless-stopped
    environment:
      - VK_GROUP_TOKEN=${VK_GROUP_TOKEN}
    expose:
      - "3000"
